### ISSUE TITLE
Common ozzo repo.

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-routing#13]
Hi!
I think we need to create a common repository for discussion on common framework questions and future requests.

**Comment by qiangxue** [comment]
For now let's use this place for questions and discussions. As we have more users, we will build a website for better community support.

**Comment by kolkov** [comment]
Thanks!
I think we need to write a website on go-ozzo like in https://github.com/beego/website
It will be the best example how to use ozzo framework in practice.

**Comment by qiangxue** [comment]
Agree. We will need to create some boilerplates to show best practices. When you finish your current Go project, perhaps you can share with me your experience? After I finish mine, I will also write something.
