### ISSUE TITLE
JWT Authorization

### ISSUE THREAD

**Issue by vvv-v13** [go-ozzo/ozzo-routing#15]
Hi, 
I wrote middleware for JWT authorization for your framework go-ozzo, ozzo-routing.
If You want i can transfer code of JWT for you without any  limits from me
I have plan to write tests for this code and fix comments in code

https://github.com/vvv-v13/ozzo-jwt

Thanks.

**Comment by qiangxue** [comment]
It looks great!

How about we adding a link to your repo in the README file here? I hope this would work better for you than transferring your code to me.

**Comment by vvv-v13** [comment]
> How about we adding a link to your repo in the README file here? 
I agree, it will be very good.
Thank you.

**Comment by SpiLLeR** [comment]
Thank you! Good component. 

I will trying use it in my sandbox application. Now we look on go-ozzo for development.
