### ISSUE TITLE
Subdomains with ozzo-routing

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-routing#17]
What is the best way to working with subdomains in ozzo-routing?

**Comment by kolkov** [comment]
Hi! @qiangxue, how about this question?

**Comment by qiangxue** [comment]
How do you plan to use it?

**Comment by kolkov** [comment]
api.mydomain.com, portal.mydomain.com etc.

**Comment by kolkov** [comment]
Much like here:
https://medium.com/russian/a-cartoon-intro-to-redux-e2108896f7e6#.1iiab1ufc
