### ISSUE TITLE
关于context中handler是否能够放到router中

### ISSUE THREAD

**Issue by skyleelove** [go-ozzo/ozzo-routing#20]
强哥，context中的router是否可以放在router的结构体中呢？该怎么做

**Comment by qiangxue** [comment]
不太明白你的需求……每个context实例都有它自己特定的handlers（根据当前请求而定的）。

**Comment by skyleelove** [comment]
我的想法是router决定上下文，所以觉着handler放在router中更佳合适，强哥这样做会有影响么？

**Comment by qiangxue** [comment]
针对每个context，你需要知道handlers以及当前正在处理的handler index。这些信息可以放在router，但是这样一来就需要通过加锁来防止不同goroutine之间的数据访问竞争问题。

**Comment by qiangxue** [comment]
早期的几个go routing framework都没有context概念（你可以认为这就是context被解耦到极致了），而是通过一个共享变量来进行handler之间的数据共享。由于需要加锁保护这个变量访问，这类框架的性能都有问题，而且从结构上也显得很原始。

**Comment by skyleelove** [comment]
如果把handler放到router中的话，该如何加锁呢？因为想深层次的学习下，所以想由浅入深的学习。

**Comment by qiangxue** [comment]
router中定义个map，key是context或者request，value是对应的handler列表以及当前在执行的handler下标。因为map不是 thread-safe的，所以访问它的时候需要用mutex保护。

**Comment by skyleelove** [comment]
将handler放在context中，hander访问的时候为什么不用加锁呢？

**Comment by qiangxue** [comment]
因为每个context只给一个goroutine访问。
