### ISSUE TITLE
关于context中data  map[string]interface{}作用？

### ISSUE THREAD

**Issue by skyleelove** [go-ozzo/ozzo-routing#21]
您好，
请问context中的变量data有什么作用呢，想把他利用起来，却无从下手，求解答。

**Comment by qiangxue** [comment]
主要是middleware和handler之间用来数据通讯用的。比如你可以有一个专门做验证的middleware，验证后把用户ID写到这里context.Set("UserID", userID)。之后在handler就可以根据需要取回它了：context.Get("UserID")
