### ISSUE TITLE
Error in JWT example 

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-routing#24]
Hi! I think this is a error:
```
 token, err := auth.NewJWT(jwt.StandardClaims{
         Id: id
       }, signingKey)
```

```
func NewJWT(claims jwt.MapClaims, signingKey string, signingMethod ...jwt.SigningMethod) (string, error) {
	var sm jwt.SigningMethod = jwt.SigningMethodHS256
	if len(signingMethod) > 0 {
		sm = signingMethod[0]
	}
	return jwt.NewWithClaims(sm, claims).SignedString([]byte(signingKey))
}
```

**Comment by kolkov** [comment]
`return c.Write(fmt.Sprint("Welcome, %v!", claims.Id)` missing a closing bracket

**Comment by vvv-v13** [comment]
Hi.
I use this code,  in my project i store id in account_id field.
```
claims := c.Get("JWT").(*jwt.Token).Claims.(jwt.MapClaims)
accountID := claims["account_id"].(string)

```

**Comment by qiangxue** [comment]
@kolkov Thanks. Is missing the closing bracket the only problem?
@vvv-v13 Thanks for sharing!

**Comment by kolkov** [comment]
@qiangxue No, main problem is:
`cannot use jwt.StandardClaims literal (type jwt.StandardClaims) as type jwt.MapClaims in argument to auth.NewJWT`

**Comment by qiangxue** [comment]
ah, you are right. The example code was written for an old version of the implementation. Just fixed it. Thanks.
