### ISSUE TITLE
关于优雅重启的问题？

### ISSUE THREAD

**Issue by skyleelove** [go-ozzo/ozzo-routing#26]
Hi，强哥：
     一直想问您，有没有写关于server优雅重启的组件。热更新配置，http请求超时处理这些功能的组件。

**Comment by qiangxue** [comment]
谢谢你的建议，这些都是很重要的组件，只是我暂时没有时间。如果你有解决方案，欢迎提交。

**Comment by qiangxue** [comment]
https://github.com/go-ozzo/ozzo-routing/commit/e09fe878a4b41a5b968469ef4d15df56c2bab849
