### ISSUE TITLE
auth.JWT使用动态密钥

### ISSUE THREAD

**Issue by telnetor** [go-ozzo/ozzo-routing#27]
Hi,强哥
在使用auth.JWT过程中，signingKey是根据二级域名动态变化的，那么我要如何使用 r.Use(auth.JWT(signingKey)) ？

**Comment by qiangxue** [comment]
一个办法是修改JWTOptions, 添加GetVerificationKey属性。如果这个属性非空，每次就调用它生成一个key。

**Comment by qiangxue** [comment]
Fixed by https://github.com/go-ozzo/ozzo-routing/pull/28
谢谢！
