### ISSUE TITLE
JSON default charset?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-routing#36]
Hi!
How to set default charset UTF-8 for json writer?
by default I see:
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 16 May 2017 16:55:58 GMT
Transfer-Encoding: chunked
```
https://youtrack.jetbrains.com/issue/WEB-24771

**Comment by qiangxue** [comment]
As you wrote in the jetbrains issue, JSON should be encoded in unicode. Why would you set the charset in the header?

**Comment by kolkov** [comment]
Thanks! I think that is a JetBrains bug!
