### ISSUE TITLE
Serving static files with processed URL

### ISSUE THREAD

**Issue by byanjiong** [go-ozzo/ozzo-routing#45]
I want to serve images, and those images are saved in a tree-structure directories. The images are saved in the directory based on their first 3 characters of their name.

**Example:**

If user:
1. `GET /uploads/t4s1h9k0px12.jpg`, then serve `/uploads/t/4/s/t4s1h9k0px12.jpg`
2. `GET /uploads/ya5sx76hgx21_b_adbj65xcgd16.jpg`, then serve `/uploads/y/a/5/ya5sx76hgx21_b_adbj65xcgd16.jpg`

How can I use the `file.Server`? How to configure the `file.PathMap`?

```
router.Get("/*", file.Server(file.PathMap{
	"/": "/ui/",
}))
```

Do I need to implement a **custom routing handler** that process the URL, and then just use the standard **http** library `http.ServeContent` to serve the corresponding file?

**Comment by qiangxue** [comment]
Yes, a custom handler is needed. You may refer to file.Server when implementing it.
