### ISSUE TITLE
"Routing.context" vs standard library "context" package

### ISSUE THREAD

**Issue by byanjiong** [go-ozzo/ozzo-routing#49]
It seems that the "`Routing.context`" is handling a goroutine process, quite similar to the standard library "`context`" package.

However, the standard library's "`context`" interface have:
```go
type Context interface {
    Done() <-chan struct{}
    Err() error
    Deadline() (deadline time.Time, ok bool)
    Value(key interface{}) interface{}
}
```

Is it possible to implement those methods in the "`Routing.context`"?

I am using other library which uses the standard library "`context`" as shwon

```go
ctx := context.Background()
posts, resp, err := client.GetPosts.List(ctx, opt)
```

If the "Routing.context" implements the interface's methods, probably I can just wired the function in a routing handler as such

```go
func getAllPost(c *routing.Context) error {
    posts, resp, err := client.GetPosts.List(c, opt)
    //...
}
```

Else, may I know what is the best way to create a `context` within a `routing context`?

Any reason not to implement the standard "context" method in "routing.context"? I am new to Go, may please advice... ^_^

**Comment by qiangxue** [comment]
You can use this: `c.Request.Context()`

**Comment by byanjiong** [comment]
Yeah, it works. Thanks...
