### ISSUE TITLE
Error in Serving Static Files section

### ISSUE THREAD

**Issue by mistbow-git** [go-ozzo/ozzo-routing#5]
Hi! I try to run code sample:

r := routing.NewRouter()
// serves the files under working-dir/web/assets
r.To("/assets(/.*)?", routing.Static("web"))

But Error is:
not enough arguments in call to routing.Static

if I use:
// serves the files under working-dir/web/assets
	st := routing.StaticOptions{"", "", nil}
	r.To("(/.*)?", routing.Static("/", st))

everything is working

Thanks!

**Comment by qiangxue** [comment]
This is expected. Go doesn't support optional parameters (can only use `...Type` to do this, which is ugly).

**Comment by mistbow-git** [comment]
But this code shown in README. 
```go
r := routing.NewRouter()
// serves the files under working-dir/web/assets
r.To("/assets(/.*)?", routing.Static("web"))
```

**Comment by qiangxue** [comment]
ah, I see. I just changed the code to make the options optional. Thanks!
