### ISSUE TITLE
VGO support.

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-routing#51]
Hi!
Are you planning to add VGO support?

**Comment by kolkov** [comment]
@qiangxue What about VGO?

**Comment by kolkov** [comment]
Is it possiple to change releases tags according to [symver](https://semver.org/)?
![image](https://user-images.githubusercontent.com/3740898/41654494-5155d380-7492-11e8-8916-f4abadd15186.png)

**Comment by kolkov** [comment]
Hi! Any plans on this?

**Comment by kolkov** [comment]
Hi! Ping...

**Comment by qiangxue** [comment]
Closing as it has been implemented.

**Comment by kolkov** [comment]
Thanks! Super!
