### ISSUE TITLE
Error handling is not conform with OpenAPI standard

### ISSUE THREAD

**Issue by donutloop** [go-ozzo/ozzo-routing#53]
the router sets for each error case a content type "text/plain" but that behavior is to static. Could you introduce a customizable error handler that the user can decide self what kind of content he wants sending to the cunsomer back or you could extending the collection of http errors (JSON, XML, Text, etc) and error matching.

<img width="695" alt="bildschirmfoto 2018-07-10 um 09 53 54" src="https://user-images.githubusercontent.com/9432921/42496801-797cdee0-8427-11e8-9e7c-5b4be058ca25.png">

Behavior of content type
 Type
    https://tools.ietf.org/search/rfc2616#section-7.2
Entity body
    https://tools.ietf.org/search/rfc2616#section-7.2.1

**Comment by donutloop** [comment]
A middleware triggers the same behavior, I`m right with that assumption?

<img width="716" alt="bildschirmfoto 2018-07-12 um 12 31 29" src="https://user-images.githubusercontent.com/9432921/42628190-9af3373c-85cf-11e8-8ea1-3f03c5d9b75b.png">

**Comment by qiangxue** [comment]
Your error handler middleware can be something like the following:

```go
func ErrorHandler(c *routing.Context) (err error) {
	defer func() {
		if e := recover(); e != nil {
            // handle panic here
		}

		if err != nil {
			// handle normal error here (e.g. send error in json response)
			c.Abort()
		}
	}()

	return c.Next()
}
```

**Comment by donutloop** [comment]
Done! Thank you for your offered support!
