### ISSUE TITLE
Bypass handler

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-routing#58]
Hi!
Is a way to bypass handler in server func? I try to find way to bypass auth handler for public routes. 
Or the best way to have  diferent routes for private and public?

**Comment by qiangxue** [comment]
You should use route groups. One route group for public routes, the other installed with auth middleware for private routes.

**Comment by kolkov** [comment]
Thanks! Now I understand that there is no other option for skipping one of the handlers.
