### ISSUE TITLE
How to Organize a project?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-routing#6]
In PHP we create root folder and project in it. Such as:
```
root
-config
-controllers
-models
-views
-utils
-vendor
etc.
```
My project is an angular.js project.
I need to have one or more index.html file(s) which will load some .js and .css files.
And then Angular.js on frontend will use REST API on backend. 

Golang is not a PHP.
Qiang, what is the best way to organaize a project in the root folder?
What do you think about this?
Thanks!

**Comment by qiangxue** [comment]
Currently, my project is organized as follows - not the best way for sure. As said before, I'm using gulp to build code (both go and js code). Your idea is very welcome.

```
/
    server.go             the main file
    config/               
        app.go            App object populated with config
        app.json          base json config
        app.dev.json      env specific config
    users/                user-related features/APIs
        handlers.go       user routes and handlers
        payload.go        input/output structs for user APIs
    posts/
        handlers.go
        payload.go
    common/               shared constructs
        models.go         data models
        services.go       services supporting features
    ui/                   contains AngularJS app
        index.html
        app/
```

**Comment by mistbow-git** [comment]
Qiang, help me please!
if I using 
```
-controllers
-models
```
how can I use a package names?
For example:
Folder Controllers,
all files with the same name?
package controllers in users.go
package controllers in films.go
package controllers in actors.go
and the same in models folder?

And what can me do if i want to create some modules as in yii2?
And if I want to create a subfolders in controllers and models?

**Comment by qiangxue** [comment]
You should forget about PHP and Yii2 controllers. :)
Use Go packages to divide and modularize your code.
My previous project org is based on functionalities. The overall goal is to make each package self contained with the only dependency on shared/reusable packages (e.g. the models, services).

**Comment by mistbow-git** [comment]
Easy to say! It's a different philosophy...)))

**Comment by qiangxue** [comment]
Closed as the suggestion was given. Further discussion can be made elsewhere.
