### ISSUE TITLE
What is meaning of ozzo? Could your provide its road map? Thanks.

### ISSUE THREAD

**Issue by ScottHuangZL** [go-ozzo/ozzo-routing#7]
Dear Qian,

I use Yii1/2 for create some web solutions:) Thanks for your fantastic framework.

We know the trend will be more JS frontend + RESTful backend, so that may be your reason to start pay time to golang, and create new web framework.  

Could you advise what is the meaning of ozzo?
In one of your article, you compare many routing fw, do the ozzo will be beat them:)
And what is your philosophy and road map for this ozzo web framework?  

I would like to be act as early adopter:) Thanks.

Regards,
Scott Huang

**Comment by qiangxue** [comment]
Thanks for trying ozzo. :) The name is a coined one which has no specific meaning except ease of memorizing. 

In terms of performance, ozzo-routing currently doesn't beat others. However, I'm working on a new version which is expected to improve the current performance by one or two magnitudes. 

Ozzo aims to be a loosely coupled, enterprise-ready, and full stack Web framework. While it is far from being complete, you can start to use one or a few of its components (e.g. routing, logging, dbx) in your projects, thanks to its loosely coupled architecture. 

Let me know if you encounter any problem. Thanks!
