### ISSUE TITLE
404 error while trying to request / 

### ISSUE THREAD

**Issue by MetalGuardian** [go-ozzo/ozzo-routing#9]
I receive 404 error while trying to request / 
```
2016/01/02 15:33:17 [127.0.0.1] [0.095ms] GET / HTTP/1.1 404 9
```
using the example code 
```
r.Get("", func(c *routing.Context) {
	c.Write("Welcome, ozzo!")
})
```

If I change code to 
```
r.Get("/", func(c *routing.Context) {...})
```
then request is successful 

Tests are running successfully

**Comment by mistbow-git** [comment]
Hi! Qiang changed the source code and documentation. Now it is not work! (
Example from English README.md
```Go
// set up routes and handlers
    r.Get("", func(c *routing.Context) {
        fmt.Fprint(c.Response, "Go ozzo!")
    })
```

**Comment by qiangxue** [comment]
Core code and readme are both fixed. Thanks!
